# Generated by Django 5.0.7 on 2024-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
    ]
