# Generated by Django 5.0.7 on 2024-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
